services:
  node:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-node
    container_name: kuboniku-node
    environment:
      - LOCAL_IP_ADDR=${LOCAL_IP_ADDR}
    volumes:
      - ./:/home/app
      - node_modules_volume:/home/app/node_modules
    ports:
      - 3000:3000
      - 8080:8080
    tty: true

volumes:
  node_modules_volume:
